[project]
name = "rag-venv"
version = "0.1.0"
description = "initial package list and dependencies"
authors = [
    {name = "Mamoot"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "haystack (>=0.42,<0.43)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
